Repository opexdev/server-stack, pull requests merged in 2022-05, with the labels that each got.

#1 Decouple configs
  .github/workflows/pr.yml
  Jenkinsfile
  dev.Jenkinsfile
  docker-stack.dev.yml
  docker-stack.override.yml
  docker-stack.yml
Labels: enhancement

#2 Release v1.0.0-beta.1
  .github/workflows/pr.yml
  Jenkinsfile
  dev.Jenkinsfile
  docker-stack.dev.yml
  docker-stack.override.yml
  docker-stack.yml
Labels: bug, enhancement

#3 Release v1.0.0-beta.1
  Jenkinsfile
  dev.Jenkinsfile
  docker-stack.dev.yml
  docker-stack.override.yml
  docker-stack.yml
Labels: bug, enhancement

#4 Release v1.0.0-beta.2
  docker-stack.yml
Labels: bug

#5 Add superset url env to admin panel
  docker-stack.yml
Labels: bug
